"""Added resources

Revision ID: 44606745f055
Revises: bb6e5ce834bf
Create Date: 2025-03-26 19:42:31.471791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44606745f055'
down_revision = 'bb6e5ce834bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_ts', sa.DateTime(), nullable=True),
    sa.Column('updated_ts', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('internal_filename', sa.String(length=255), nullable=False),
    sa.Column('external_link', sa.String(length=1024), nullable=True),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('memo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['memo_id'], ['memo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('internal_filename')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource')
    # ### end Alembic commands ###
